In [2]:
import numpy as np

# Creating Arrays

## Using np.`array()`

### Creating arrays from lists

> used to create a NumPy array from a list, the most common way to manually create arrays

#### Caveats/Special Notes:
  
The type of elements in the array is determined automatically, but can be explicitly specified using the dtype parameter.

All elements in the list should be of the same type, or NumPy will upcast them to the highest precision type to maintain homogeneity.

#### General Syntax
`numpy.array(object, dtype=None)`

`object`: The list or iterable to be converted into an array.

`dtype`: Desired data type of the array (optional).

In [3]:
# Creating a list
my_list = [1, 2, 3, 4, 5]

# Converting the list to a NumPy array
my_array = np.array(my_list)

# Printing the created array
print(my_array)

[1 2 3 4 5]


### Creating arrays from tuples

> used to create a NumPy array from a tuple, the most common way to manually create arrays

#### Caveats/Special Notes
  
The type of elements in the array is determined automatically, but can be explicitly specified using the dtype parameter.

All elements in the list should be of the same type, or NumPy will upcast them to the highest precision type to maintain homogeneity.

#### General Syntax
`numpy.array(object, dtype=None)`

`object`: The list or iterable to be converted into an array.

`dtype`: Desired data type of the array (optional).

In [4]:
# Creating a tuple
my_tuple = (1, 2, 3, 4, 5)

# Converting the tuple to a NumPy array
my_array = np.array(my_tuple)

# Printing the created array
print(my_array)


[1 2 3 4 5]


## Special Array Functions

### np.`zeros()`

> creates a new NumPy array filled entirely with zeros. This function is often used for initializing an array to a known size before filling it with actual data.

#### Caveats/Special Notes

The shape of the array must be specified as a tuple. For a 1-D array, use a single integer or a one-element tuple.

The data type defaults to float64 but can be specified using the dtype parameter.

#### General Syntax

`numpy.zeros(shape, dtype=float)`

`shape`: The shape of the new array (e.g., (2, 3) for a 2x3 array).

`dtype`: Desired data type of the array (optional).

In [5]:
# Creating a 2x3 array of zeros
zero_array = np.zeros((2, 3))

# Printing the created array
print(zero_array)


[[0. 0. 0.]
 [0. 0. 0.]]


### np.`arrange()`

> creates an array with evenly spaced values within a given interval. It's similar to Python's built-in `range()` function but returns a NumPy array.


#### Caveats/Special Notes

The end value in the specified interval is not included in the array.

Be cautious with floating-point arguments due to the inexact representation of such values.

#### General Syntax
`numpy.arange(start, stop, step, dtype=None)`

`start`: Start of interval (optional; default is 0).

`stop`: End of interval (not included in the array).

`step`: Spacing between values (optional; default is 1).

`dtype`: The type of the output array (optional).




In [3]:
# Creating an array from 0 to 9
arange_array = np.arange(10)

# Creating an array from 10 to 20 with a step of 2
arange_step_array = np.arange(10, 21, 2)

# Printing the created arrays
print("Regular range:", arange_array)
print("Range with step:", arange_step_array)


Regular range: [0 1 2 3 4 5 6 7 8 9]
Range with step: [10 12 14 16 18 20]


### np.`full()`

> creates a new NumPy array of a specified shape and fills it with a specified value. This function is useful when you need an array with a constant value.

#### Caveats/Special Notes

The shape of the array must be defined as a tuple or integer.

The data type of the array is inferred from the fill value but can be explicitly set with the dtype parameter.


#### General Syntax

`numpy.full(shape, fill_value, dtype=None)`

`shape`: The shape of the new array, e.g., (2, 3) for a 2x3 array.

`fill_value`: The value to fill the array with.

`dtype`: Desired data type of the array (optional).


In [12]:
# Creating a 3x3 array filled with the number 7
full_array = np.full((3, 3), 7)

# Printing the created array
print(full_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


### np.`linspace()`

> creates an array of specified size filled with evenly spaced values over a specified interval. Unlike np.arange(), which uses step size, 
> lets you specify the exact number of elements you want.

#### Caveats/Special Notes

The end value of the interval is included by default, unlike `np.arange()`.

#### General Syntax

`numpy.linspace(start, stop, num=50, dtype=None)`

`start`: Starting value of the sequence.

`stop`: End value of the sequence.

`num`: Number of samples to generate (default is 50).

`dtype`: The type of the output array (optional).

In [6]:
# Creating an array of 5 numbers, evenly spaced between 0 and 1
linspace_array = np.linspace(0, 1, 5)

# Printing the created array
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


# Operations on Arrays

## Basic Operations

### np.`add()`



> performs element-wise addition between two arrays. If given two arrays of the same shape, it adds corresponding elements together. 

#### Caveats/Special Notes

The two arrays must be broadcastable to the same shape. Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations.

If the arrays are not of the same shape, NumPy tries to broadcast them to a compatible shape, which can sometimes lead to unexpected results or errors if not properly understood.


#### General Syntax

`numpy.add(x1, x2)`

`x1`, `x2`: Input arrays to be added

In [16]:
# Creating two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Element-wise addition of array1 and array2
result = np.add(array1, array2)

# Printing the result
print(result)

[5 7 9]


### np.`sqrt()`

> computes the square root of each element in the input array.

#### Caveats/Special Notes

The function returns NaNs (not a number) for any negative elements in the array since the square root of a negative number is not defined in real numbers.

The data type of the output array is usually a floating-point number, even if the input array contains integers.

#### General Syntax

`numpy.sqrt(x)`

`x`: Input array.


In [17]:
# Creating an array
array = np.array([1, 4, 9, 16, 25])

# Applying square root to each element
sqrt_array = np.sqrt(array)

# Printing the result
print(sqrt_array)

[1. 2. 3. 4. 5.]


### np.`exp()`

> calculates the exponential e^x of all elements in the input array.

#### Caveats/Special Notes

The exponential function can quickly lead to very large numbers, so be cautious with large inputs, as this might result in overflow errors or very large outputs.

The function typically returns a floating-point array regardless of the input array's data type.

#### General Syntax

`numpy.exp(x)`

`x`: Input array.


In [7]:
# Creating an array
array = np.array([0, 1, 2, 3, 4])

# Calculating the exponential of each element
exp_array = np.exp(array)

# Printing the result
print(exp_array)

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


## Random Number Generation

### np.random.`random()`

> is used to generate an array of random floats in the half-open interval [0.0,1.0)
> 
> closed interval - [
> 
> open interval - )

#### Caveats/Special Notes

none


#### General Syntax

`numpy.random.random(size=None)`

`size`: The shape of the output array. If not provided, a single float is returned.

In [8]:
# Generating a 2x3 array of random floats
random_array = np.random.random((2, 3))

# Printing the created array
print(random_array)

[[0.30216205 0.2379832  0.05316925]
 [0.72567021 0.53679656 0.64065986]]


### np.random.`randint()`

> generates an array of random integers from a specified low (inclusive) to a high (exclusive) value.

#### Caveats/Special Notes

The low value is inclusive, and high is exclusive. If high is omitted, the range is assumed to be from 0 to low.

#### General Syntax

`numpy.random.randint(low, high=None, size=None, dtype='l')`

`low`: Lowest (inclusive) integer to be drawn from the distribution.

`high`: One above the highest integer to be drawn from the distribution.

`size`: The shape of the output array.

`dtype`: Desired data type of the result.



In [21]:
# Generating a 2x2 array of random integers between 0 and 10
random_int_array = np.random.randint(0, 10, size=(2, 2))

# Printing the created array
print(random_int_array)

[[3 3]
 [8 6]]


# Array Manipulation

## Reshaping and Flattening

### np.`reshape()`

> changes the shape of an array without changing its data. It's a versatile tool for manipulating the dimensions of an existing array

#### Caveats/Special 

The new shape must be compatible with the size of the original array, meaning the total number of elements must remain constant.

The function returns a new view of the array whenever possible; however, it might return a copy if necessary.

Using -1 as one of the dimensions in the new shape lets NumPy automatically calculate the size of that dimension.


#### General Syntax

`numpy.reshape(a, newshape)`

`a`: Array to be reshaped.

`newshape`: The new shape should be compatible with the original shape.


In [16]:
# Creating an array
original_array = np.arange(6)
0 
# Reshaping the array to 2x3
reshaped_array = np.reshape(original_array, (2, 3))


# Printing the original and reshaped arrays
print("Original Array:", original_array)
print("Reshaped Array:", reshaped_array)

Original Array: [0 1 2 3 4 5]
Reshaped Array: [[0 1 2]
 [3 4 5]]


### np.`flatten()`

> is used to flatten a multi-dimensional array into a one-dimensional array. This function returns a copy of the array collapsed into one dimension.
#### Caveats/Special Notes

Unlike np.`ravel()`, which returns a flattened array view if possible, np.`flatten()` always returns a copy. This means changes to the flattened array will not affect the original array.




#### General Syntax

`ndarray.flatten()`


In [25]:
# Creating a 2x3 array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Flattening the array
flattened_array = original_array.flatten()

# Printing the original and flattened arrays
print("Original Array:\n", original_array)
print("Flattened Array:", flattened_array)

Original Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]


### np.`ravel()`

> flattens a multi-dimensional array into a one-dimensional array. It returns a contiguous flattened array, ideally as a view (not a copy) of the original array, which means changes to the returned array may affect the original array.

#### Caveats/Special Notes

more memory effiicent than flatten

#### General Syntax

`numpy.ravel(a)`

`a`: Array to be flattened.



In [26]:
# Creating a 2x3 array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Flattening the array using ravel
raveled_array = np.ravel(original_array)

# Printing the original and raveled arrays
print("Original Array:\n", original_array)
print("Raveled Array:", raveled_array)

Original Array:
 [[1 2 3]
 [4 5 6]]
Raveled Array: [1 2 3 4 5 6]


## Array Slicing

> Array slicing in NumPy is a technique to access a subset of an array. It allows you to retrieve specific elements, rows, columns, or sub-arrays from an array based on their index positions.

#### Caveats/Special Notes

Slicing in NumPy, similar to Python lists, is zero-indexed.

The slice start:stop:step includes start index, but excludes stop index.

Slices of arrays do not return copies; they return views. Hence, modifying a slice modifies the original array.

Negative indices can be used to count from the end of the array.


#### General Syntax

1-D array: `array[start:stop:step]`

2-D array (or higher): `array[start_row:stop_row:step_row, start_col:stop_col:step_col]`

In [27]:
# Creating a 1-D array
one_d_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Slicing the array from index 2 to 7
sliced_array = one_d_array[2:7]

# Creating a 2-D array
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing the 2-D array to get the first two rows and columns
sliced_2d_array = two_d_array[:2, :2]

# Printing the results
print("Sliced 1-D Array:", sliced_array)
print("Sliced 2-D Array:\n", sliced_2d_array)

Sliced 1-D Array: [2 3 4 5 6]
Sliced 2-D Array:
 [[1 2]
 [4 5]]


# Attributes of ndarray

## Key Attributes

### `ndim`

> The ndim attribute of a NumPy array returns the number of dimensions of the array, also known as the array's rank

#### Caveats/Special Notes

A 1-D array will have ndim equal to 1, a 2-D array will have ndim equal to 2, and so on.

The ndim attribute is particularly helpful in conditional statements where the code behavior might depend on the dimensionality of the input array.

#### General Syntax
Syntax: `array.ndim`


In [28]:
# Creating a 1-D array
one_d_array = np.array([1, 2, 3, 4, 5])

# Creating a 2-D array
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])

# Getting the dimensions of the arrays
dim_one_d = one_d_array.ndim
dim_two_d = two_d_array.ndim

# Printing the dimensions
print("Dimension of 1-D array:", dim_one_d)
print("Dimension of 2-D array:", dim_two_d)

Dimension of 1-D array: 1
Dimension of 2-D array: 2


### `shape`

> The shape attribute of a NumPy array returns a tuple representing the dimensions of the array. Each element of the tuple indicates the size of the array along that dimension. 

#### Caveats/Special Notes

For a 2-D array, the shape would be (n_rows, n_columns).

For a 1-D array, the shape is (n_elements,) – note the comma, indicating it's a single-dimensional tuple.



#### General Syntax

Syntax: `array.shape`

In [29]:
# Creating a 1-D array
one_d_array = np.array([1, 2, 3, 4, 5])

# Creating a 2-D array
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])

# Getting the shapes of the arrays
shape_one_d = one_d_array.shape
shape_two_d = two_d_array.shape

# Printing the shapes
print("Shape of 1-D array:", shape_one_d)
print("Shape of 2-D array:", shape_two_d)

Shape of 1-D array: (5,)
Shape of 2-D array: (2, 3)


### `size`

> The size attribute of a NumPy array returns the total number of elements in the array.


#### Caveats/Special Notes

The size of an array is equal to the product of its dimensions.

#### General Syntax

Syntax: `array.size`


In [30]:
# Creating a 1-D array
one_d_array = np.array([1, 2, 3, 4, 5])

# Creating a 2-D array
two_d_array = np.array([[1, 2, 3], [4, 5, 6]])

# Getting the sizes of the arrays
size_one_d = one_d_array.size
size_two_d = two_d_array.size

# Printing the sizes
print("Size of 1-D array:", size_one_d)
print("Size of 2-D array:", size_two_d)

Size of 1-D array: 5
Size of 2-D array: 6


### `dtype`

> The dtype attribute of a NumPy array indicates the data type of the elements in the array. NumPy arrays are homogenous, meaning all elements in the array are of the same type. 

#### Caveats/Special Notes

The data type can be explicitly set when creating an array using the dtype parameter.

#### General Syntax

Syntax: `array.dtype`

### `itemsize`

> The itemsize attribute of a NumPy array returns the size (in bytes) of each element in the array. It reflects the memory occupied by each array element, which is directly tied to the array's data type

#### Caveats/Special Notes

The value of itemsize depends on the data type of the array. For example, int32 has an itemsize of 4 bytes, while float64 has an itemsize of 8 bytes.


#### General Syntax

Syntax: `array.itemsize`


In [33]:
# Creating an array
array = np.array([1, 2, 3, 4], dtype=np.float64)

# Getting the item size of the array
item_size = array.itemsize

# Printing the item size
print("Item size of the array:", item_size, "bytes")

Item size of the array: 8 bytes


### `T`

> The T attribute of a NumPy array returns the transpose of the array. For a 2-D array, this means swapping rows with columns. For a 1-D array, the transpose returns the array itself as transposing does not change its shape.


#### Caveats/Special Notes

For arrays with more than two dimensions, T returns the transposed array with its axes reversed.

The transpose operation does not involve copying data, but it returns a view of the original array. Therefore, modifying the transposed array will also modify the original array.


#### General Syntax

Syntax: `array.T`


In [34]:
# Creating a 2-D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Transposing the array
transposed_array = array_2d.T

# Printing the original and transposed arrays
print("Original Array:\n", array_2d)
print("Transposed Array:\n", transposed_array)

Original Array:
 [[1 2 3]
 [4 5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


# Practice Questions

Write Python program to Create a 5 * 6 array between 10 to 1000 such that the difference between the elements are 12 and they are only even numbers. 

Print the even rows and odd columns from the array.


In [ ]:
# Write Python program to Create a 5 * 6 array between 10 to 1000 such that the difference between the elements are 12 and they are only even numbers. 

# Print the even rows and odd columns from the array.

import numpy as np

array = np.arange(10,1000,12)


array = array[:30]


array = array.reshape((5,6))


print(array[0::2,1::2])

Take user input for dimension of matrix and create the following pattern. 

Below is for 8 * 8 pattern.


![8X8 Pattern](../images/numpy-pattern.png)

In [ ]:
import numpy as np

def dynamic_checkerboard(n):
    """
    Create an n x n checkerboard pattern using NumPy, where n is given by the user.
    """
    # Initialize an n x n array of zeros
    board = np.zeros((n, n), dtype=int)
    
    # Use slicing to set the required indices to 1
    board[1::2, ::2] = 1  # Set 1s for even-indexed rows on odd-indexed columns
    board[::2, 1::2] = 1  # Set 1s for odd-indexed rows on even-indexed columns
    
    return board

# Example for a 5x5 matrix
checkerboard_pattern_dynamic = dynamic_checkerboard(5)
print(checkerboard_pattern_dynamic)


Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit  degrees and vice versa. 

Values are stored into a NumPy array.

In [ ]:
# Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit  degrees and vice versa. 

# Values are stored into a NumPy array.

import numpy as np

def convert_to_celsius(arr):
    return (arr - 32) * 5/9

def convert_to_fahrenheit(arr):
    return (arr * 9/5) + 32


cels = np.array([0,25,100])
print(convert_to_fahrenheit(cels))
fars = np.array([32,77,212])
print(convert_to_celsius(fars))